### ISSUE TITLE
Plugin fails on Netlify for valid static assets

### ISSUE THREAD

**Issue by Thoughtscript** [Munter/netlify-plugin-checklinks#114]
Hi!

Great plugin so far. Ran into an issue on Netlify:

<img width="965" alt="Screen Shot 2020-05-27 at 3 54 06 PM" src="https://user-images.githubusercontent.com/10905039/83080170-61552380-a032-11ea-8509-d0f42f861017.png">

Using: https://www.brokenlinkcheck.com - none of the assets above fail for: https://thoughtscript.io (note that some of the academic articles behind paywalls might despite being perfectly valid).

Thanks!

**Comment by Munter** [comment]
Interesting case. 

Your image URL is actually traversing out of your web root. From /blog/*.html you start your href with ../../

That would place the assets folder next to your web root, which does indeed seem wrong, since you're now in the area of the filesystem that only netlify controls.

I bet that browser behavior allows you to but any number of extra ../ at the beginning of a URL, but clamps you at the web root. But the plug-in is file based.

I'll need to think a bit about what the best behavior would be here. My initial feeling is that URLs should work even without the dependence on any web server or browser behavior

**Comment by Thoughtscript** [comment]
Thanks for the prompt reply - I appreciate the extra consideration.

I had originally planned on migrating static images (which I believe are the culprits here) over to a dedicated CDN (but ended up leaving them in Netlify/Gitlab since it was so convenient!).

That being said I think relative paths are used elsewhere without a problem. Resolution of this issue would be helpful (cutting down a bit on post-processing time for me) - if only to throw a warning rather than stop the entire build/deploy.

My thanks!

**Comment by Munter** [comment]
I'm marking this as won't fix. I think href's should be correct, and not depend on a user agent stripping excessive prepended `../`'s
